package com.makers.makersbnb.controllers;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;

@RestController
public class StaticPageController {
    @GetMapping("/")
    public ModelAndView landingPage() {
        ModelAndView modelAndView = new ModelAndView("/LandingPage");
        // for now, imagine this value was generated by querying the database
        Integer nSpaces = 100;
        // this next line makes nSpaces available in the template
        modelAndView.addObject("nSpaces", nSpaces);
        return modelAndView;
    }

    @GetMapping("/contactus")
    public String contactUs() {
        return "email@website.com";
    }

    @GetMapping("/termsandconditions")
    public String termsAndConditions() {
        return "Coming soon! In the meantime, please behave yourselves.";
    }

}
